### ISSUE TITLE
Almost all functionallity don't work

### ISSUE THREAD

**Issue by oleksandr-shkovyra** [cfpb/hubot-aws-cfpb#28]
Hi,
i would like to use this functionallity, but i am getting an errors:

while i am trying to make ec2 ls:
```
null
[Wed Jul 19 2017 17:01:34 GMT+0300 (EEST)] ERROR TypeError: Cannot read property 'html_url' of undefined
  at /Users/laptop_name/git/botops/node_modules/hubot-aws-cfpb/scripts/ec2/ls.coffee:221:7, <js>:317:19
  at gist (/Users/laptop_name/git/botops/node_modules/quick-gist/lib/index.js:28:12)
  at handle_sending_message (/Users/laptop_name/git/botops/node_modules/hubot-aws-cfpb/scripts/ec2/ls.coffee:220:5, <js>:312:14)
  at /Users/laptop_name/git/botops/node_modules/hubot-aws-cfpb/scripts/ec2/ls.coffee:226:5, <js>:325:14
  at Response.<anonymous> (/Users/laptop_name/git/botops/node_modules/hubot-aws-cfpb/scripts/ec2/ls.coffee:76:7, <js>:102:16)
  at Request.<anonymous> (/Users/laptop_name/git/botops/node_modules/aws-sdk/lib/request.js:350:18)
  at Request.callListeners (/Users/laptop_name/git/botops/node_modules/aws-sdk/lib/sequential_executor.js:100:18)
  at Request.emit (/Users/laptop_name/git/botops/node_modules/aws-sdk/lib/sequential_executor.js:77:10)
  at Request.emit (/Users/laptop_name/git/botops/node_modules/aws-sdk/lib/request.js:604:14)
  at Request.transition (/Users/laptop_name/git/botops/node_modules/aws-sdk/lib/request.js:21:12)
  at AcceptorStateMachine.runTo (/Users/laptop_name/git/botops/node_modules/aws-sdk/lib/state_machine.js:14:12)
  at /Users/laptop_name/git/botops/node_modules/aws-sdk/lib/state_machine.js:26:10
  at Request.<anonymous> (/Users/laptop_name/git/botops/node_modules/aws-sdk/lib/request.js:22:9)
  at Request.<anonymous> (/Users/laptop_name/git/botops/node_modules/aws-sdk/lib/request.js:606:12)
  at Request.callListeners (/Users/laptop_name/git/botops/node_modules/aws-sdk/lib/sequential_executor.js:104:18)
  at Request.emit (/Users/laptop_name/git/botops/node_modules/aws-sdk/lib/sequential_executor.js:77:10)
  at Request.emit (/Users/laptop_name/git/botops/node_modules/aws-sdk/lib/request.js:604:14)
  at Request.transition (/Users/laptop_name/git/botops/node_modules/aws-sdk/lib/request.js:21:12)
  at AcceptorStateMachine.runTo (/Users/laptop_name/git/botops/node_modules/aws-sdk/lib/state_machine.js:14:12)
  at /Users/laptop_name/git/botops/node_modules/aws-sdk/lib/state_machine.js:26:10
  at Request.<anonymous> (/Users/laptop_name/git/botops/node_modules/aws-sdk/lib/request.js:22:9)
  at Request.<anonymous> (/Users/laptop_name/git/botops/node_modules/aws-sdk/lib/request.js:606:12)
  at Request.callListeners (/Users/laptop_name/git/botops/node_modules/aws-sdk/lib/sequential_executor.js:104:18)
  at Request.emit (/Users/laptop_name/git/botops/node_modules/aws-sdk/lib/sequential_executor.js:77:10)
  at Request.emit (/Users/laptop_name/git/botops/node_modules/aws-sdk/lib/request.js:604:14)
  at Request.transition (/Users/laptop_name/git/botops/node_modules/aws-sdk/lib/request.js:21:12)
  at AcceptorStateMachine.runTo (/Users/laptop_name/git/botops/node_modules/aws-sdk/lib/state_machine.js:14:12)
  at /Users/laptop_name/git/botops/node_modules/aws-sdk/lib/state_machine.js:26:10
  at Request.<anonymous> (/Users/laptop_name/git/botops/node_modules/aws-sdk/lib/request.js:22:9)
  at Request.<anonymous> (/Users/laptop_name/git/botops/node_modules/aws-sdk/lib/request.js:606:12)
  at Request.callListeners (/Users/laptop_name/git/botops/node_modules/aws-sdk/lib/sequential_executor.js:104:18)
  at Request.emit (/Users/laptop_name/git/botops/node_modules/aws-sdk/lib/sequential_executor.js:77:10)
  at Request.emit (/Users/laptop_name/git/botops/node_modules/aws-sdk/lib/request.js:604:14)
  at Request.transition (/Users/laptop_name/git/botops/node_modules/aws-sdk/lib/request.js:21:12)
  at AcceptorStateMachine.runTo (/Users/laptop_name/git/botops/node_modules/aws-sdk/lib/state_machine.js:14:12)
  at /Users/laptop_name/git/botops/node_modules/aws-sdk/lib/state_machine.js:26:10
  at Request.<anonymous> (/Users/laptop_name/git/botops/node_modules/aws-sdk/lib/request.js:22:9)
  at Request.<anonymous> (/Users/laptop_name/git/botops/node_modules/aws-sdk/lib/request.js:606:12)
  at Request.callListeners (/Users/laptop_name/git/botops/node_modules/aws-sdk/lib/sequential_executor.js:104:18)
  at callNextListener (/Users/laptop_name/git/botops/node_modules/aws-sdk/lib/sequential_executor.js:90:14)
  at IncomingMessage.onEnd (/Users/laptop_name/git/botops/node_modules/aws-sdk/lib/event_listeners.js:201:11)
  at emitNone (events.js:110:20)
  at IncomingMessage.emit (events.js:207:7)
  at endReadableNT (_stream_readable.js:1047:12)
  at _combinedTickCallback (internal/process/next_tick.js:102:11)
  at process._tickDomainCallback (internal/process/next_tick.js:198:9)
```

while i am trying to make ec2 stop instance:
```
Inspecting instance [instance-id] for permission to run this operation
{ dry_run: false,
  Filters: [ { Name: 'tag:Creator', Values: [ undefined ] } ] }
[Wed Jul 19 2017 16:55:07 GMT+0300 (EEST)] ERROR TypeError: path must be a string or Buffer
  at Object.fs.openSync (fs.js:651:18)
  at Object.fs.readFileSync (fs.js:553:33)
  at CSON.parseCSONFile (/Users/laptop_name/git/botops/node_modules/cson/out/lib/cson.js:332:23)
  at Object.addSubnetFilter (/Users/laptop_name/git/botops/node_modules/hubot-aws-cfpb/scripts/ec2/restrictor.coffee:19:14, <js>:25:21)
  at Object.authorizeOperation (/Users/laptop_name/git/botops/node_modules/hubot-aws-cfpb/scripts/ec2/restrictor.coffee:41:17, <js>:52:30)
  at TextListener.callback (/Users/laptop_name/git/botops/node_modules/hubot-aws-cfpb/scripts/ec2/start_instance.coffee:61:5, <js>:68:25)
  at executeListener (/Users/laptop_name/git/botops/node_modules/hubot/src/listener.coffee:65:11, <js>:53:19)
  at allDone (/Users/laptop_name/git/botops/node_modules/hubot/src/middleware.coffee:44:37, <js>:34:16)
  at /Users/laptop_name/git/botops/node_modules/async/lib/async.js:274:13
  at Object.async.eachSeries (/Users/laptop_name/git/botops/node_modules/async/lib/async.js:142:20)
  at Object.async.reduce (/Users/laptop_name/git/botops/node_modules/async/lib/async.js:268:15)
  at /Users/laptop_name/git/botops/node_modules/hubot/src/middleware.coffee:49:7, <js>:37:22
  at _combinedTickCallback (internal/process/next_tick.js:95:7)
  at process._tickDomainCallback (internal/process/next_tick.js:198:9)
```

**Comment by imuchnik** [comment]
@cfifua Sorry for such delayed response. It is a little hard to tell what bot command you are running and what client you are using, but it seems your tags are not well defined. As for ls command, the error you are seeing is due to a dependency on  our gist script and corresponding variables that need to be set.
